mirror:
    script:
        - apk update && apk add git
        - git config --global push.default simple
        - git push https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/bunn804/bun-sync-test.git HEAD:master