mirror:
    script:
        - apk update && apk add git
        - git config --global push.default simple
        - git remote set-url origin https://github.com/bunn804/bun-sync-test.git
        - git push https://github.com/bunn804:${GITHUB_TOKEN}/bun-sync-test.git HEAD:master